//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atrakcje
    {
        public int Id_atrakcji { get; set; }
        public Nullable<int> Id_wycieczki { get; set; }
        public string Rodzaj { get; set; }
    
        public virtual Wycieczki Wycieczki { get; set; }
    }
}
