//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotele
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotele()
        {
            this.Wycieczki = new HashSet<Wycieczki>();
        }
    
        public int Id_hotelu { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> Standard { get; set; }
        public string Kraj { get; set; }
        public string Miasto { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Witryna { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wycieczki> Wycieczki { get; set; }
    }
}
