//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BiuroPodrozyEntities : DbContext
    {
        public BiuroPodrozyEntities()
            : base("name=BiuroPodrozyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atrakcje> Atrakcje { get; set; }
        public virtual DbSet<Hotele> Hotele { get; set; }
        public virtual DbSet<Klienci> Klienci { get; set; }
        public virtual DbSet<Rezydenci> Rezydenci { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uczestnicy> Uczestnicy { get; set; }
        public virtual DbSet<Usługi> Usługi { get; set; }
        public virtual DbSet<Wycieczki> Wycieczki { get; set; }
        public virtual DbSet<Zamówienia> Zamówienia { get; set; }
    }
}
