//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uczestnicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uczestnicy()
        {
            this.Zamówienia = new HashSet<Zamówienia>();
        }
    
        public int Id_uczestnika { get; set; }
        public Nullable<int> Id_klienta { get; set; }
        public string Imię { get; set; }
        public string Nazwisko { get; set; }
        public string Pesel { get; set; }
        public Nullable<System.DateTime> DataUrodzenia { get; set; }
        public string MiejsceUrodzenia { get; set; }
        public string Adres { get; set; }
        public string Miasto { get; set; }
        public string Kod_pocztowy { get; set; }
        public string Kraj { get; set; }
        public string Telefon { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamówienia> Zamówienia { get; set; }
    }
}
