//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamówienia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamówienia()
        {
            this.Uczestnicy = new HashSet<Uczestnicy>();
        }
    
        public int Id_zamówienia { get; set; }
        public Nullable<int> Id_wycieczki { get; set; }
        public Nullable<int> Id_Klienta { get; set; }
        public Nullable<System.DateTime> Data_zamówienia { get; set; }
        public Nullable<int> Ilość_miejsc { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Data_płatności { get; set; }
        public string Typ_płatności { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Wycieczki Wycieczki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uczestnicy> Uczestnicy { get; set; }
    }
}
